### ISSUE TITLE
Weight Map

### ISSUE THREAD

**Issue by njust-lyy** [khdlr/HED-UNet#13]
Hello, I want to know how to set the weight value in the weight map. Is there an example? thank you!

**Comment by khdlr** [comment]
Hi there! The idea is that the model learns to predict an optimal weight map by itself. However, if you'd lilke to set your own weight maps manually, you will need to change these lines: https://github.com/khdlr/HED-UNet/blob/master/deep_learning/models/hed_unet.py#L85-L87

**Comment by njust-lyy** [comment]
Oh, thank you!
