### ISSUE TITLE
Testing data

### ISSUE THREAD

**Issue by Malaika68** [khdlr/HED-UNet#4]
After training.. how can we test our data?

**Comment by Malaika68** [comment]
Can you please help in tiling and stitching data?

**Comment by khdlr** [comment]
Hi Malaika, this paper might help: https://arxiv.org/abs/1805.12219

**Comment by Malaika68** [comment]
Hey thanks for the help. dimensions of my dataset image are 57x60. but it does not train on that dimension. Can ypu please tell where i can change the dimensions in the code?

**Comment by Malaika68** [comment]
Also please tell me that why it is cropping my image from side after training?

**Comment by khdlr** [comment]
That's because the input dimensions should be a multiple of 32 (this is a limitation that all UNet-based models share in a similar fashion).

You could try padding the inputs to a size of 64x64.

**Comment by Malaika68** [comment]
Okay  great.. I have tried that. Also can you please tell the channels of images and its labels. Because I am getting channels dimension error. If the channels of images and labels are 3 or 1?

**Comment by khdlr** [comment]
You can set the number of input channels in `config.yml` (`model_args.input_channels`), it should be 3 by default. Labels should have 1 as the channel dimension.
