### ISSUE TITLE
Whether this program can handle .png files. If you can’t handle it, can you convert the .tif file to a .png file?

### ISSUE THREAD

**Issue by lisongyu111** [khdlr/HED-UNet#5]

**Comment by khdlr** [comment]
Hi there, this shouldn't be a problem. You can replace the .tif loading with .png loading code (e.g. using PIL).

Look back at https://github.com/khdlr/HED-UNet/issues/3#issuecomment-918969745, you essentially want to implement the `load_image` method as `np.asarray(PIL.Image.open('<imagepath>.png'))`
