### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by lisongyu111** [khdlr/HED-UNet#7]

**Comment by khdlr** [comment]
This sounds like you are inputting images with 4 channels while having the model configured to take 3 channels as inputs.

As you were mentioning png inputs earlier, I'm assuming that you're reading the data as RGBA instead of RGB.

If you do not need the fourth channel, you can strip it away (`img = img[:3]`). If you do indeed need the fourth channel, you can set `input_channels: 4` in the `config.yml` file.

**Comment by lisongyu111** [comment]
I used an image converter to convert the 3-channel png image to an image in pt format




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "khdlr/HED-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [khdlr/HED-UNet] RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead (#7)





 
This sounds like you are inputting images with 4 channels while having the model configured to take 3 channels as inputs.
 
As you were mentioning png inputs earlier, I'm assuming that you're reading the data as RGBA instead of RGB.
 
If you do not need the fourth channel, you can strip it away (img = img[:3]). If you do indeed need the fourth channel, you can set input_channels: 4 in the config.yml file.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lisongyu111** [comment]
I used an image converter to convert a 3-channel png image into a tiff format image.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "khdlr/HED-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [khdlr/HED-UNet] RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead (#7)





 
This sounds like you are inputting images with 4 channels while having the model configured to take 3 channels as inputs.
 
As you were mentioning png inputs earlier, I'm assuming that you're reading the data as RGBA instead of RGB.
 
If you do not need the fourth channel, you can strip it away (img = img[:3]). If you do indeed need the fourth channel, you can set input_channels: 4 in the config.yml file.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lisongyu111** [comment]
I put my image in according to the format in your code, 512*512 tif image.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "khdlr/HED-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [khdlr/HED-UNet] RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead (#7)





 
This sounds like you are inputting images with 4 channels while having the model configured to take 3 channels as inputs.
 
As you were mentioning png inputs earlier, I'm assuming that you're reading the data as RGBA instead of RGB.
 
If you do not need the fourth channel, you can strip it away (img = img[:3]). If you do indeed need the fourth channel, you can set input_channels: 4 in the config.yml file.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by khdlr** [comment]
Can you make sure that the loaded image array has only 3 channels? I.e. by adding `print(img.shape)` to the `full_forward` method in `train.py`?

**Comment by lisongyu111** [comment]
The image I input is 512*512*3 but I don't know why it is 256*256*4.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "khdlr/HED-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [khdlr/HED-UNet] RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead (#7)





 
Can you make sure that the loaded image array has only 3 channels? I.e. by adding print(img.shape) to the full_forward method in train.py?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by khdlr** [comment]
Assuming you're using the provided INRIA data loading code, that will tile each input image into tiles of 256x256 (see the `TILESIZE = 256` constant in `deep_learning/utils/data.py`.

I still believe that the fourth channel comes from the alpha channel in the png, could you simply cut it off by changing `data = raster.read()` to `data = raster.read()[:3]` in `deep_learning/utils/data.py` (and then also removing the cached `.npz` files?)

**Comment by lisongyu111** [comment]
Thank you for your answer, but my data set is a tif image converted from a png image. I am using pictures in tif format.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "khdlr/HED-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [khdlr/HED-UNet] RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead (#7)





 
Assuming you're using the provided INRIA data loading code, that will tile each input image into tiles of 256x256 (see the TILESIZE = 256 constant in deep_learning/utils/data.py.
 
I still believe that the fourth channel comes from the alpha channel in the png, could you simply cut it off by changing data = raster.read() to data = raster.read()[:3] in deep_learning/utils/data.py (and then also removing the cached .npz files?)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by khdlr** [comment]
Yes but png files can have 4 channels, and when you convert them to tiff that 4th channel is probably kept. Could you please simply try the solution I suggested? Or what do you expect me to do here?

**Comment by lisongyu111** [comment]
I see what you mean. I'll check my picture. Thank you for your reply.



发自我的iPhone


------------------ Original ------------------
From: Konrad Heidler ***@***.***&gt;
Date: Thu,Oct 14,2021 4:23 PM
To: khdlr/HED-UNet ***@***.***&gt;
Cc: lisongyu111 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [khdlr/HED-UNet] RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[8, 4, 256, 256] to have 3 channels, but got 4 channels instead (#7)





 
Yes but png files can have 4 channels, and when you convert them to tiff that 4th channel is probably kept. Could you please simply try the solution I suggested? Or what do you expect me to do here?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
